---
# tasks file for immich

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ immich_user_uid }}"
    group: "{{ immich_user_gid }}"
    mode: "0755"
  loop:
    - "{{ immich_host_dir }}"
    - "{{ immich_host_dir }}/postgres"
    - "{{ immich_host_dir }}/redis"
    - "{{ immich_storage_dir }}"
    - "{{ immich_storage_dir }}/encoded-video"
    - "{{ immich_storage_dir }}/library"
    - "{{ immich_storage_dir }}/thumbs"
    - "{{ immich_storage_dir }}/profile"
    - "{{ immich_storage_dir }}/upload"
    - "{{ immich_storage_dir }}/backups"
  loop_control:
    loop_var: item
  tags: update_immich

- name: Set permission for redis directory
  file:
    path: "{{ immich_host_dir }}/redis"
    state: directory
    owner: "999"
    group: "999"
    mode: "0755"
  tags: update_immich

- name: Create .immich file in data folders
  ansible.builtin.file:
    path: "{{ item }}/.immich"
    state: touch
    owner: "{{ immich_user_uid }}"
    group: "{{ immich_user_gid }}"
    mode: "0644"
  loop:
    - "{{ immich_storage_dir }}/library"
    - "{{ immich_storage_dir }}/encoded-video"
    - "{{ immich_storage_dir }}/thumbs"
    - "{{ immich_storage_dir }}/profile"
    - "{{ immich_storage_dir }}/upload"
    - "{{ immich_storage_dir }}/backups"
  loop_control:
    loop_var: item
  tags: update_immich

- name: Generate docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ immich_host_dir }}/docker-compose.yml"
    owner: "{{ immich_user_uid }}"
    group: "{{ immich_user_gid }}"
    mode: "0644"
  tags: 
    - update_immich
    - update_docker_compose

- name: Run docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ immich_host_dir }}"
    state: present
  tags: 
    - update_immich
    - update_docker_compose
