---
# tasks file for immich

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ immich_uid }}"
    group: "{{ immich_gid }}"
    mode: "0755"
    recurse: true
  loop:
    - "{{ immich_host_dir }}"
    - "{{ immich_db_dir }}"
    - "{{ immich_redis_dir }}"
    - "{{ immich_data_dir }}/encoded-video"
    - "{{ immich_data_dir }}/library"
    - "{{ immich_data_dir }}/thumbs"
    - "{{ immich_data_dir }}/profile"
    - "{{ immich_data_dir }}/upload"
    - "{{ immich_data_dir }}/backups"
  loop_control:
    loop_var: item

- name: Set permission for redis directory
  ansible.builtin.file:
    path: "{{ immich_redis_dir }}"
    state: directory
    owner: "{{ immich_redis_uid }}"
    group: "{{ immich_redis_gid }}"
    mode: "0755"

- name: Create .immich file in data folders
  ansible.builtin.file:
    path: "{{ item }}/.immich"
    state: touch
    owner: "{{ immich_uid }}"
    group: "{{ immich_gid }}"
    mode: "0644"
  loop:
    - "{{ immich_data_dir }}/library"
    - "{{ immich_data_dir }}/encoded-video"
    - "{{ immich_data_dir }}/thumbs"
    - "{{ immich_data_dir }}/profile"
    - "{{ immich_data_dir }}/upload"
    - "{{ immich_data_dir }}/backups"
  loop_control:
    loop_var: item

- name: Copy hardware acceleration configuration file
  ansible.builtin.copy:
    src: "hwaccel.ml.yml"
    dest: "{{ immich_host_dir }}/hwaccel.ml.yml"
    owner: "{{ immich_uid }}"
    group: "{{ immich_gid }}"
    mode: "0644"
  when: immich_ml_hw_accel_enabled

- name: Docker tasks
  notify: Run docker compose
  tags: update_docker_compose
  block:
    - name: Generate environment file
      ansible.builtin.template:
        src: env.j2
        dest: "{{ immich_host_dir }}/.env"
        owner: "{{ immich_uid }}"
        group: "{{ immich_gid }}"
        mode: "0644"

    - name: Generate docker compose file
      ansible.builtin.template:
        src: docker-compose.j2
        dest: "{{ immich_host_dir }}/docker-compose.yml"
        owner: "{{ immich_uid }}"
        group: "{{ immich_gid }}"
        mode: "0644"
